export const TODAYS_FIXTURES_START = "TODAYS_FIXTURES_START";
export const TODAYS_FIXTURES_SUCCESS = "TODAYS_FIXTURES_SUCCESS";
export const TODAYS_FIXTURES_FAIL = "TODAYS_FIXTURES_FAIL";
export const GET_FLAGS = "GET_FLAGS";

export const GET_ALL_FIXTURES_START = "GET_ALL_FIXTURES_START";
export const GET_ALL_FIXTURES_SUCCESS = "GET_ALL_FIXTURES_SUCCESS";
export const GET_ALL_FIXTURES_FAIL = "GET_ALL_FIXTURES_FAIL";

export const BETS_START = "BETS_START";
export const BET_START = "BET_START";
export const GET_BETS_SUCCESS = "GET_BETS_SUCCESS";
export const GET_USER_BETS_SUCCESS = "GET_USER_BETS_SUCCESS";
export const ADD_USER_BET_SUCCESS = "ADD_USER_BET_SUCCESS";
export const REMOVE_USER_BET_SUCCESS = "REMOVE_USER_BET_SUCCESS";
export const CHANGE_USER_BET_SUCCESS = "CHANGE_USER_BET_SUCCESS";
export const BETS_FAIL = "BETS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SCORE_START = "SCORE_START";
export const SCORE_SUCCESS = "SCORE_SUCCESS";
export const SCORE_FAIL = "SCORE_FAIL";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const GET_USERS_START = "GET_USERS_START";

